### ISSUE TITLE
Throws error when button is inside the form

### ISSUE THREAD

**Issue by maddygoround** [remotty/angular-ladda#44]
When applying ladda to the button which is within the form then its throws error

TypeError: r[0].querySelector is not a function
    at link (http://localhost/loopin/bower_components/angular-ladda/dist/angular-ladda.min.js:2:880)
    at ka (http://localhost/loopin/bower_components/angular/angular.min.js:79:16)
    at u (http://localhost/loopin/bower_components/angular/angular.min.js:66:326)
    at g (http://localhost/loopin/bower_components/angular/angular.min.js:58:136)
    at u (http://localhost/loopin/bower_components/angular/angular.min.js:66:270)
    at g (http://localhost/loopin/bower_components/angular/angular.min.js:58:136)
    at g (http://localhost/loopin/bower_components/angular/angular.min.js:58:153)
    at g (http://localhost/loopin/bower_components/angular/angular.min.js:58:153)
    at g (http://localhost/loopin/bower_components/angular/angular.min.js:58:153)
    at g (http://localhost/loopin/bower_components/angular/angular.min.js:58:153) 

When button is outside the form everything works fine.

**Comment by subicura** [comment]
Can you tell me browser name and version?
